# Generated by Django 4.1.5 on 2023-01-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('kg', 'Kilogram'), ('dona', 'Dona')], max_length=10)),
                ('miqdor', models.IntegerField()),
                ('narx', models.IntegerField()),
                ('export_vaqt', models.DateTimeField()),
                ('izoh', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Export',
                'verbose_name_plural': 'Export',
            },
        ),
        migrations.CreateModel(
            name='Hodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_sharif', models.CharField(max_length=200)),
                ('lavozim', models.CharField(max_length=100)),
                ('stavka', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hodim',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('kg', 'Kilogram'), ('dona', 'Dona')], max_length=10)),
                ('miqdor', models.IntegerField()),
                ('narx', models.IntegerField()),
                ('import_vaqt', models.DateTimeField()),
                ('izoh', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Import',
            },
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('ism_sharif', models.CharField(max_length=200)),
                ('telefon', models.IntegerField()),
                ('manzil', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('kg', 'Kilogram'), ('dona', 'Dona')], max_length=10)),
                ('narx', models.IntegerField()),
                ('miqdor', models.IntegerField()),
                ('izoh', models.TextField(blank=True, null=True)),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mijoz')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborxona',
            },
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('dona', 'Dona')], max_length=10, null=True)),
                ('narx', models.IntegerField()),
                ('miqdor', models.IntegerField()),
                ('buyurtma_sana', models.DateTimeField()),
                ('izoh', models.TextField(blank=True, null=True)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mijoz')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
